name: inha_notice
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  html: ^0.15.0
  flutter_background_service: ^5.1.0
  flutter_local_notifications: ^19.3.0
  path_provider: ^2.0.14
  cupertino_icons: ^1.0.8
  url_launcher: ^6.1.8
  flutter_dotenv: ^6.0.0
  xml: ^6.5.0
  intl: ^0.20.1
  shared_preferences: ^2.3.5
  sqflite: ^2.4.1
  path: ^1.9.0
  firebase_core: ^4.2.0
  firebase_messaging: ^16.0.3
  logger: ^2.5.0
  flutter_inappwebview: ^6.1.5
  share_plus: ^12.0.1
  pull_to_refresh: ^2.0.0
  charset_converter: ^2.3.0
  flutter_bloc: ^9.1.1
  dartz: ^0.10.1
  equatable: ^2.0.7
  get_it: ^9.2.0
  freezed_annotation: ^3.1.0
  http_status_code: ^0.0.2
  skeletonizer: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  freezed: ^3.2.3

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/onboarding.png
    - assets/licenses/licenses.json
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Black.otf
        - asset: assets/fonts/Pretendard-Bold.otf
        - asset: assets/fonts/Pretendard-ExtraBold.otf
        - asset: assets/fonts/Pretendard-ExtraLight.otf
        - asset: assets/fonts/Pretendard-Light.otf
        - asset: assets/fonts/Pretendard-Medium.otf
        - asset: assets/fonts/Pretendard-Regular.otf
        - asset: assets/fonts/Pretendard-SemiBold.otf
        - asset: assets/fonts/Pretendard-Thin.otf
          weight: 700
    - family: TossFaceFontMac
      fonts:
        - asset: assets/fonts/TossFaceFontMac.ttf
    - family: NanumGothic
      fonts:
        - asset: assets/fonts/NanumGothic.otf
        - asset: assets/fonts/NanumGothicBold.otf
        - asset: assets/fonts/NanumGothicExtraBold.otf
        - asset: assets/fonts/NanumGothicLight.otf